export const gridLayouts = {
  xl: [
    { i: "todayMetricsChart", x: 0, y: 0, w: 6, h: 5 },
    { i: "visitorInsightChart", x: 6, y: 0, w: 6, h: 7 },
    { i: "userRegionChart", x: 12, y: 0, w: 3, h: 5 },
    { i: "revenueChart", x: 0, y: 2, w: 6, h: 15, minH: 15 },
    { i: "productSalesCategoryChart", x: 6, y: 2, w: 6, h: 7 },
    { i: "productBubbleChart", x: 6, y: 2, w: 6, h: 7 },
    { i: "inventoryLevelChart", x: 0, y: 6, w: 4, h: 3 },
    { i: "orderFulfillmentChart", x: 4, y: 6, w: 4, h: 3 },
    { i: "conversionFunnelChart", x: 8, y: 6, w: 4, h: 3 },
    { i: "productPerformanceRadarChart", x: 0, y: 9, w: 8, h: 2 },
    { i: "topProducts", x: 8, y: 9, w: 4, h: 2 },
    { i: "orderStatusDistributionChart", x: 0, y: 11, w: 12, h: 3 },
    { i: "salesTrendsComposedChart", x: 0, y: 14, w: 12, h: 3 },
  ],
  lg: [
    { i: "todayMetricsChart", x: 0, y: 0, w: 3, h: 2 },
    { i: "visitorInsightChart", x: 3, y: 0, w: 3, h: 2 },
    { i: "userRegionChart", x: 6, y: 0, w: 3, h: 2 },
    { i: "revenueChart", x: 9, y: 0, w: 3, h: 15, minH: 14 },
    { i: "productSalesCategoryChart", x: 0, y: 2, w: 6, h: 6 },
    { i: "productBubbleChart", x: 6, y: 2, w: 6, h: 4 },
    { i: "inventoryLevelChart", x: 0, y: 6, w: 4, h: 3 },
    { i: "orderFulfillmentChart", x: 4, y: 6, w: 4, h: 3 },
    { i: "conversionFunnelChart", x: 8, y: 6, w: 4, h: 3 },
    { i: "productPerformanceRadarChart", x: 0, y: 9, w: 8, h: 2 },
    { i: "topProducts", x: 8, y: 9, w: 4, h: 2 },
    { i: "orderStatusDistributionChart", x: 0, y: 11, w: 12, h: 3 },
    { i: "salesTrendsComposedChart", x: 0, y: 14, w: 12, h: 3 },
  ],
  md: [
    { i: "todayMetricsChart", x: 0, y: 0, w: 6, h: 2 },
    { i: "visitorInsightChart", x: 6, y: 0, w: 6, h: 2 },
    { i: "userRegionChart", x: 0, y: 2, w: 6, h: 2 },
    { i: "revenueChart", x: 6, y: 2, w: 6, h: 15, minH: 14 },
    { i: "productSalesCategoryChart", x: 0, y: 4, w: 12, h: 4 },
    { i: "productBubbleChart", x: 0, y: 8, w: 12, h: 4 },
    { i: "inventoryLevelChart", x: 0, y: 12, w: 6, h: 3 },
    { i: "orderFulfillmentChart", x: 6, y: 12, w: 6, h: 3 },
    { i: "conversionFunnelChart", x: 0, y: 15, w: 12, h: 3 },
    { i: "productPerformanceRadarChart", x: 0, y: 18, w: 8, h: 2 },
    { i: "topProducts", x: 8, y: 18, w: 4, h: 2 },
    { i: "orderStatusDistributionChart", x: 0, y: 20, w: 12, h: 3 },
    { i: "salesTrendsComposedChart", x: 0, y: 23, w: 12, h: 3 },
  ],
  sm: [
    { i: "todayMetricsChart", x: 0, y: 0, w: 12, h: 2 },
    { i: "visitorInsightChart", x: 0, y: 2, w: 12, h: 2 },
    { i: "userRegionChart", x: 0, y: 4, w: 12, h: 2 },
    { i: "revenueChart", x: 0, y: 6, w: 12, h: 15, minH: 15 },
    { i: "productSalesCategoryChart", x: 0, y: 8, w: 12, h: 4 },
    { i: "productBubbleChart", x: 0, y: 12, w: 12, h: 4 },
    { i: "inventoryLevelChart", x: 0, y: 16, w: 12, h: 3 },
    { i: "orderFulfillmentChart", x: 0, y: 19, w: 12, h: 3 },
    { i: "conversionFunnelChart", x: 0, y: 22, w: 12, h: 3 },
    { i: "productPerformanceRadarChart", x: 0, y: 25, w: 12, h: 2 },
    { i: "topProducts", x: 0, y: 27, w: 12, h: 2 },
    { i: "orderStatusDistributionChart", x: 0, y: 29, w: 12, h: 3 },
    { i: "salesTrendsComposedChart", x: 0, y: 32, w: 12, h: 3 },
  ],
};
