// app/layout.tsx (or app/layout.js)
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Setup Poppins with a variable name (optional)
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      {/* Apply Poppins globally */}
      <body>{children}</body>
    </html>
  );
}
